

const fetchItems = () => {
  const data = [
    {
      id: 10,
      category: 'Fruits and Vegetables',
      brand: 'Fresho',
      title: 'Potato',
      availableQuantity: 50,
      cost: 10,
      description: '1 kg',
      imageUrl: 'https://blog.oxforddictionaries.com/wp-content/uploads/potato.jpg',
    },
    {
      id: 20,
      category: 'Fruits and Vegetables',
      brand: 'Fresho',
      title: 'Guava',
      availableQuantity: 60,
      cost: 40,
      description: '0.5 kg',
      imageUrl: 'https://www.caloriesecrets.net/wp-content/uploads/2016/11/health-benefits-of-guavas.jpg',
    },
    {
      id: 30,
      category: 'Dairy',
      brand: 'Farm Fresh',
      title: 'Milk',
      availableQuantity: 70,
      cost: 22,
      description: '500ml',
      imageUrl: 'https://atmedia.imgix.net/589dd2e644dfd7a46b4cbf4871afa2a782532280?w=1500&fit=max',
    },
    {
      id: 40,
      category: 'Personal Care',
      brand: 'Nivea',
      title: 'Nivea Soft Moisturising Creme',
      availableQuantity: 80,
      cost: 100,
      description: '200ml',
      imageUrl: 'https://www.superdrug.com/medias/sys_master/front-zoom/front-zoom/8842412392478/Nivea-Soft-Refreshingly-Soft-Moisturising-Cream-200ml-89141.jpg',
    },
    {
      id: 50,
      category: 'Personal Care',
      brand: 'Dove',
      title: 'Shampoo',
      availableQuantity: 90,
      cost: 340,
      description: '400ml',
      imageUrl: 'https://media6.ppl-media.com/tr:h-750,w-750,c-at_max/static/img/product/114529/dove-oxygen-moisture-shampoo-650-ml_1_display_1467106396_d439b98f.jpg',
    },
    {
      id: 60,
      category: 'Personal Care',
      brand: 'Himalaya',
      title: 'Face wash',
      availableQuantity: 100,
      cost: 99,
      description: '100ml',
      imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/51WYviiyYCL._SL1000_.jpg',
    },
    {
      id: 70,
      category: 'Personal Care',
      brand: 'Garnier',
      title: 'Micellar cleansing water',
      availableQuantity: 50,
      cost: 399,
      description: '150ml',
      imageUrl: 'https://s4.thcdn.com/productimg/600/600/11171628-1534330378330716.jpg',
    },
    {
      id: 80,
      category: 'Personal Care',
      brand: 'Parachute',
      title: 'Coconut hair oil',
      availableQuantity: 60,
      cost: 155,
      description: '500ml',
      imageUrl: 'https://www.bigbasket.com/media/uploads/p/l/1201527_1-parachute-coconut-oil-100-pure-500-ml-advansed-coconut-oil-75-ml.jpg',
    },
    {
      id: 90,
      category: 'Dairy',
      brand: 'Amul',
      title: 'Butter',
      availableQuantity: 70,
      cost: 225,
      description: '1 kg',
      imageUrl: 'https://4.imimg.com/data4/XB/GO/GLADMIN-11048885/amul-butter-500x500.jpg',
    },
    {
      id: 100,
      category: 'Dairy',
      brand: 'Amul',
      title: 'Paneer',
      availableQuantity: 80,
      cost: 75,
      description: '250gm',
      imageUrl: 'https://5.imimg.com/data5/AK/VA/MY-9101930/amul-fresh-paneer-500x500.jpg',
    },
    {
      id: 110,
      category: 'Dairy',
      brand: 'Amul',
      title: 'Cheese slices',
      availableQuantity: 90,
      cost: 99,
      description: '10 slices',
      imageUrl: 'http://eboxmart.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/m/amul_chees_10_slice_200_gm__470_1_2.jpg',
    },
    {
      id: 120,
      category: 'Dairy',
      brand: 'Amul',
      title: 'Buttermilk',
      availableQuantity: 100,
      cost: 20,
      description: '100ml',
      imageUrl: 'https://5.imimg.com/data5/KA/TL/MY-9101930/amul-buttermilk-500x500.jpg',
    },
  ];

  return Promise.resolve(data);
};

module.exports = {
  fetchItems,
};

